name: Matrix

on: [push, workflow_dispatch]

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Node node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 6   
      - name: Node node-version
        run: node -v    